-- COMPLETE DATABASE SETUP & RECOVERY SCRIPT
-- Run this in Supabase SQL Editor to initialize the entire DB schema and security

-- 1. UTILS
create extension if not exists "uuid-ossp";

-- 2. TABLE: empresas
CREATE TABLE IF NOT EXISTS public.empresas (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    nome_empresa text NOT NULL,
    email text, -- Optional based on usage
    senha text, -- Stored securely (in real app should be hashed, here plain as per current impl)
    is_admin boolean DEFAULT false,
    ultimo_login timestamptz,
    email_notificacao text,
    whatsapp_notificacao text,
    notificacoes_ativas boolean DEFAULT true,
    criado_em timestamptz DEFAULT now(),
    atualizado_em timestamptz DEFAULT now()
);

-- 3. TABLE: ias
CREATE TABLE IF NOT EXISTS public.ias (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    empresa_id uuid REFERENCES public.empresas(id),
    nome text NOT NULL,
    ativo boolean DEFAULT true,
    criado_em timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 4. TABLE: tickets
CREATE TABLE IF NOT EXISTS public.tickets (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    ticket_id serial, -- Auto-incrementing number equivalent
    numero integer GENERATED BY DEFAULT AS IDENTITY, -- Alternative if ticket_id is text
    empresa_id uuid REFERENCES public.empresas(id),
    titulo text,
    descricao text,
    o_que_deveria_acontecer text,
    ai_id uuid REFERENCES public.ias(id),
    ai_name text,
    status text DEFAULT 'Pending',
    urgencia text,
    solucao text,
    resolvido_por text,
    resolvido_em timestamptz,
    solicitacao_info text,
    resposta_cliente text,
    aguardando_info_desde timestamptz,
    solicitante_nome text,
    chat_history jsonb DEFAULT '[]'::jsonb,
    imagens jsonb DEFAULT '[]'::jsonb, -- Array of {name, url}
    imagens_solucao jsonb DEFAULT '[]'::jsonb,
    criado_em timestamptz DEFAULT now(),
    atualizado_em timestamptz DEFAULT now()
);

-- 5. TABLE: system_settings (configuracoes)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    key text UNIQUE NOT NULL,
    value jsonb,
    updated_at timestamptz DEFAULT now()
);

-- 6. SECURITY RPC: create_empresa_secure
CREATE OR REPLACE FUNCTION create_empresa_secure(
  p_nome_empresa text,
  p_senha text,
  p_is_admin boolean DEFAULT false
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_empresa_id uuid;
  exists_check int;
BEGIN
  IF p_nome_empresa IS NULL OR p_nome_empresa = '' THEN
    RETURN json_build_object('success', false, 'error', 'Nome da Empresa é obrigatório');
  END IF;

  SELECT count(*) INTO exists_check FROM empresas WHERE nome_empresa = p_nome_empresa;
  IF exists_check > 0 THEN
    RETURN json_build_object('success', false, 'error', 'Empresa já cadastrada');
  END IF;

  INSERT INTO empresas (nome_empresa, senha, is_admin)
  VALUES (p_nome_empresa, p_senha, p_is_admin)
  RETURNING id INTO new_empresa_id;

  RETURN json_build_object('success', true, 'data', new_empresa_id);
EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- 7. SECURITY RPC: login_empresa
CREATE OR REPLACE FUNCTION login_empresa(
    p_nome_empresa text,
    p_senha text
)
RETURNS table (
    id uuid,
    nome_empresa text,
    is_admin boolean,
    email_notificacao text,
    whatsapp_notificacao text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT e.id, e.nome_empresa, e.is_admin, e.email_notificacao, e.whatsapp_notificacao
    FROM empresas e
    WHERE e.nome_empresa = p_nome_empresa AND e.senha = p_senha;
END;
$$;


-- 8. PERMISSIONS & HARDENING
-- Enable RLS (Row Level Security) - Best Practice
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE ias ENABLE ROW LEVEL SECURITY;

-- Revoke direct Insert on empresas (Force use of RPC)
REVOKE INSERT ON TABLE empresas FROM public;
REVOKE INSERT ON TABLE empresas FROM anon;
REVOKE INSERT ON TABLE empresas FROM authenticated;

-- Allow RPC execution
GRANT EXECUTE ON FUNCTION create_empresa_secure TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION login_empresa TO anon, authenticated, service_role;

-- Policies (Simple permissive for now to restore function, can be tightened later)
-- Allow Public Read for now to avoid breaking basic fetch logic if auth is loose
CREATE POLICY "Public Read Empresas" ON empresas FOR SELECT USING (true);
CREATE POLICY "Public Read Tickets" ON tickets FOR SELECT USING (true);
CREATE POLICY "Public Insert Tickets" ON tickets FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Tickets" ON tickets FOR UPDATE USING (true);
CREATE POLICY "Public Read Ias" ON ias FOR SELECT USING (true);

-- INITIAL SEED (Create Default Admin if not exists)
DO $$
DECLARE
    admin_exists int;
BEGIN
    SELECT count(*) INTO admin_exists FROM empresas WHERE nome_empresa = 'Admin';
    IF admin_exists = 0 THEN
        PERFORM create_empresa_secure('Admin', 'admin', true);
    END IF;
END $$;
